
name: 'Lock Threads'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          issue-lock-inactive-days: '181'
          issue-exclude-created-before: ''
          issue-exclude-labels: ''
          issue-lock-labels: ''
          issue-lock-comment: >
            This issue has been automatically locked since there 
            has not been any recent activity after it was closed.
          issue-lock-reason: 'resolved'
          pr-lock-inactive-days: '365'
          pr-exclude-created-before: ''
          pr-exclude-labels: 'wip'
          pr-lock-labels: ''
          pr-lock-comment: >
            This pull request has been automatically locked since there 
            has not been any recent activity after it was closed.
          pr-lock-reason: 'resolved'
          process-only: ''
